apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  labels:
    app: demo-app
    app.kubernetes.io/name: demo-app
    platform: enterprise-cloud-native
type: Opaque
stringData:
  DB_HOST: "mysql.default.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "demo_user"
  DB_PASSWORD: "changeme-in-production"
  DB_NAME: "demo_db"
  API_KEY: "demo-api-key-12345"
