apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/managed-by: enterprise-platform
    platform: enterprise-cloud-native
    env: dev
  annotations:
    description: "开发环境命名空间"
    created-by: "enterprise-cloud-native-platform"
spec: {}
