#!/bin/bash
###############################################################################
# 脚本名称: 03-ntp.sh
# 功能描述: 配置NTP时间同步，支持chrony和ntpd
# 适用系统: CentOS 7/8, Rocky Linux 8/9
# 依赖条件: root权限
# 作者: 运维平台团队
# 版本: 1.0.0
# 创建日期: 2026-05-09
###############################################################################
set -euo pipefail
umask 077

# ========================= 全局变量 =========================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LOG_DIR="${PROJECT_ROOT}/logs/01-init"
LOG_FILE="${LOG_DIR}/03-ntp_$(date +%Y%m%d_%H%M%S).log"
LOCK_FILE="/var/lock/03-ntp.lock"
NTP_SERVERS=(
    "ntp.aliyun.com"
    "ntp1.aliyun.com"
    "ntp.tencent.com"
    "time.windows.com"
)
CHRONY_CONF="/etc/chrony.conf"
NTP_CONF="/etc/ntp.conf"

# ========================= 颜色定义 =========================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ========================= 日志函数 =========================
log_info()    { echo -e "${GREEN}[INFO]${NC}  $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_step()    { echo -e "${CYAN}[STEP]${NC}  $(date '+%Y-%m-%d %H:%M:%S') === $* ===" | tee -a "$LOG_FILE"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }

# ========================= 错误处理 =========================
cleanup() {
    local exit_code=$?
    rm -f "$LOCK_FILE"
    if [[ $exit_code -ne 0 ]]; then
        log_error "脚本执行失败，退出码: $exit_code"
    fi
    return $exit_code
}
trap cleanup EXIT
trap 'log_error "收到信号，正在退出..."; exit 1' SIGINT SIGTERM

# ========================= 工具函数 =========================
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "此脚本必须以root权限运行"
        exit 1
    fi
}

check_lock() {
    if [[ -f "$LOCK_FILE" ]]; then
        local pid
        pid=$(cat "$LOCK_FILE" 2>/dev/null || true)
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            log_error "另一个实例正在运行 (PID: $pid)"
            exit 1
        fi
        log_warn "发现残留锁文件，已清理"
        rm -f "$LOCK_FILE"
    fi
    echo $$ > "$LOCK_FILE"
}

detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS_ID="${ID}"
        OS_VERSION="${VERSION_ID}"
        OS_NAME="${PRETTY_NAME}"
    fi
    log_info "检测到系统: ${OS_NAME:-Unknown}"
}

# ========================= NTP配置函数 =========================
install_chrony() {
    log_step "安装chrony时间同步服务"

    if command -v chronyd >/dev/null 2>&1; then
        log_info "chrony已安装，跳过"
        return 0
    fi

    case "${OS_ID}" in
        centos|rhel|rocky|almalinux)
            if [[ "${OS_VERSION%%.*}" -ge 7 ]]; then
                yum install -y chrony 2>>"$LOG_FILE"
            fi
            ;;
        *)
            log_warn "未知操作系统 ${OS_ID}，尝试使用yum安装"
            yum install -y chrony 2>>"$LOG_FILE"
            ;;
    esac

    if command -v chronyd >/dev/null 2>&1; then
        log_success "chrony安装成功"
    else
        log_error "chrony安装失败"
        return 1
    fi
}

configure_chrony() {
    log_step "配置chrony时间同步"

    # 备份原配置
    local backup="${CHRONY_CONF}.bak.$(date +%Y%m%d)"
    if [[ -f "$CHRONY_CONF" && ! -f "$backup" ]]; then
        cp "$CHRONY_CONF" "$backup"
        log_info "已备份chrony配置: $backup"
    fi

    # 生成新的chrony配置
    cat > "$CHRONY_CONF" << 'CHRONY_EOF'
# Enterprise Cloud Native Platform - Chrony Configuration
# Generated by 03-ntp.sh init script

# 使用国内NTP服务器
server ntp.aliyun.com iburst
server ntp1.aliyun.com iburst
server ntp.tencent.com iburst
server time.windows.com iburst

# 时间同步记录文件
driftfile /var/lib/chrony/drift

# 允许本地时间服务器（如果本机是NTP服务器）
# local stratum 10

# 启用时钟漂移补偿
makestep 1.0 3

# 内核实时时钟同步
rtcsync

# 允许哪些客户端同步（集群模式下取消注释）
# allow 10.0.0.0/8
# allow 172.16.0.0/12
# allow 192.168.0.0/16

# 日志配置
logdir /var/log/chrony
CHRONY_EOF

    log_success "chrony配置已更新"
}

disable_ntpd() {
    log_step "检查并停止ntpd服务（避免冲突）"

    # CentOS 7 可能使用ntpd
    if systemctl is-active ntpd >/dev/null 2>&1; then
        systemctl stop ntpd 2>/dev/null || true
        systemctl disable ntpd 2>/dev/null || true
        log_success "已停止并禁用ntpd服务"
    fi

    # 确保ntpd不会自启
    systemctl mask ntpd 2>/dev/null || true
}

start_chrony() {
    log_step "启动chrony服务"

    systemctl daemon-reload
    systemctl enable chronyd 2>>"$LOG_FILE"
    systemctl restart chronyd 2>>"$LOG_FILE"

    # 等待chrony启动
    sleep 2

    if systemctl is-active chronyd >/dev/null 2>&1; then
        log_success "chrony服务启动成功"
    else
        log_error "chrony服务启动失败"
        systemctl status chronyd --no-pager 2>&1 | tee -a "$LOG_FILE"
        return 1
    fi
}

verify_time_sync() {
    log_step "验证时间同步状态"

    # 等待同步
    sleep 3

    local sync_status
    if command -v chronyc >/dev/null 2>&1; then
        log_info "chrony活动源:"
        chronyc sources -v 2>&1 | tee -a "$LOG_FILE" || true

        sync_status=$(chronyc tracking 2>/dev/null | grep "Leap status" || echo "Unknown")
        log_info "同步状态: $sync_status"

        # 检查是否与服务器同步
        if chronyc tracking 2>/dev/null | grep -q "Synchronised"; then
            log_success "时间同步成功"
        else
            log_warn "时间同步可能尚未完成，首次同步可能需要几分钟"
        fi
    fi

    # 显示当前时间信息
    log_info "当前系统时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"
    timedatectl status 2>/dev/null | tee -a "$LOG_FILE" || true
}

# ========================= 主逻辑 =========================
main() {
    mkdir -p "$LOG_DIR"
    check_root
    check_lock
    detect_os

    log_step "阶段1-任务3: NTP时间同步配置"

    # 安装chrony
    install_chrony

    # 配置chrony
    configure_chrony

    # 停止可能冲突的ntpd
    disable_ntpd

    # 启动chrony
    start_chrony

    # 验证同步
    verify_time_sync

    log_success "阶段1-任务3完成: NTP时间同步配置成功"
}

main "$@"
