#!/bin/bash
###############################################################################
# 脚本名称: 04-kernel.sh
# 功能描述: 内核参数优化，适用于Kubernetes/Docker运行环境
# 适用系统: CentOS 7/8, Rocky Linux 8/9
# 依赖条件: root权限
# 作者: 运维平台团队
# 版本: 1.0.0
# 创建日期: 2026-05-09
###############################################################################
set -euo pipefail
umask 077

# ========================= 全局变量 =========================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LOG_DIR="${PROJECT_ROOT}/logs/01-init"
LOG_FILE="${LOG_DIR}/04-kernel_$(date +%Y%m%d_%H%M%S).log"
LOCK_FILE="/var/lock/04-kernel.lock"
SYSCTL_CONF="/etc/sysctl.d/99-enterprise-platform.conf"
LIMITS_CONF="/etc/security/limits.d/99-enterprise-platform.conf"
MODULES_CONF="/etc/modules-load.d/99-enterprise-platform.conf"

# ========================= 颜色定义 =========================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ========================= 日志函数 =========================
log_info()    { echo -e "${GREEN}[INFO]${NC}  $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_step()    { echo -e "${CYAN}[STEP]${NC}  $(date '+%Y-%m-%d %H:%M:%S') === $* ===" | tee -a "$LOG_FILE"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }

# ========================= 错误处理 =========================
cleanup() {
    local exit_code=$?
    rm -f "$LOCK_FILE"
    if [[ $exit_code -ne 0 ]]; then
        log_error "脚本执行失败，退出码: $exit_code"
    fi
    return $exit_code
}
trap cleanup EXIT
trap 'log_error "收到信号，正在退出..."; exit 1' SIGINT SIGTERM

# ========================= 工具函数 =========================
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "此脚本必须以root权限运行"
        exit 1
    fi
}

check_lock() {
    if [[ -f "$LOCK_FILE" ]]; then
        local pid
        pid=$(cat "$LOCK_FILE" 2>/dev/null || true)
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            log_error "另一个实例正在运行 (PID: $pid)"
            exit 1
        fi
        log_warn "发现残留锁文件，已清理"
        rm -f "$LOCK_FILE"
    fi
    echo $$ > "$LOCK_FILE"
}

detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS_ID="${ID}"
        OS_VERSION="${VERSION_ID}"
        OS_NAME="${PRETTY_NAME}"
    fi
    log_info "检测到系统: ${OS_NAME:-Unknown}"
}

# ========================= 内核优化函数 =========================
configure_sysctl() {
    log_step "配置内核参数优化"

    local backup="${SYSCTL_CONF}.bak.$(date +%Y%m%d)"
    if [[ -f "$SYSCTL_CONF" && ! -f "$backup" ]]; then
        cp "$SYSCTL_CONF" "$backup"
        log_info "已备份sysctl配置: $backup"
    fi

    cat > "$SYSCTL_CONF" << 'SYSCTL_EOF'
# Enterprise Cloud Native Platform - Kernel Parameters
# Generated by 04-kernel.sh init script
# 针对 Kubernetes/Docker 运行环境优化

# ==================== 网络参数优化 ====================
# 最大网络连接数
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 65535

# 网络缓冲区
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 1048576
net.core.wmem_default = 1048576

# TCP缓冲区（min default max）
net.ipv4.tcp_rmem = 4096 1048576 16777216
net.ipv4.tcp_wmem = 4096 1048576 16777216

# TCP连接优化
net.ipv4.tcp_max_syn_backlog = 65535
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 10
net.ipv4.tcp_max_tw_buckets = 65535
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_mtu_probing = 1

# 端口范围
net.ipv4.ip_local_port_range = 1024 65535

# 网桥过滤（Kubernetes需要）
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1

# IPv4转发（Kubernetes节点需要）
net.ipv4.ip_forward = 1

# 路由优化
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# IPv6（可选禁用）
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1

# ==================== 内存参数优化 ====================
# 虚拟内存
vm.swappiness = 10
vm.overcommit_memory = 1
vm.overcommit_ratio = 80
vm.panic_on_oom = 0
vm.max_map_count = 262144
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5

# 共享内存（Elasticsearch等需要）
kernel.shmmax = 68719476736
kernel.shmall = 4294967296

# ==================== 文件系统参数 ====================
fs.file-max = 2097152
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 8192
fs.inotify.max_queued_events = 65536
fs.aio-max-nr = 1048576

# ==================== 安全参数 ====================
# SYN Flood防护
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 3

# ICMP
net.ipv4.icmp_echo_ignore_broadcasts = 1

# 内核安全
kernel.randomize_va_space = 2
kernel.pid_max = 4194304

# ==================== Kube-proxy模式 ====================
# iptables模式
# net.ipv4.ip_forward = 1
# ipvs模式需要额外配置

# ==================== 连接追踪 ====================
net.netfilter.nf_conntrack_max = 1048576
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
SYSCTL_EOF

    log_success "sysctl配置已更新"
}

apply_sysctl() {
    log_step "应用内核参数"

    # 加载br_netfilter模块（桥接网络需要）
    modprobe br_netfilter 2>/dev/null || true
    modprobe overlay 2>/dev/null || true
    modprobe ip_vs 2>/dev/null || true
    modprobe ip_vs_rr 2>/dev/null || true
    modprobe ip_vs_wrr 2>/dev/null || true
    modprobe ip_vs_sh 2>/dev/null || true
    modprobe nf_conntrack 2>/dev/null || true

    # 应用sysctl参数
    sysctl --system 2>&1 | tee -a "$LOG_FILE" || true

    # 验证关键参数
    local params_to_check=(
        "net.bridge.bridge-nf-call-iptables"
        "net.ipv4.ip_forward"
        "vm.swappiness"
        "fs.file-max"
        "vm.max_map_count"
    )

    local all_ok=true
    for param in "${params_to_check[@]}"; do
        local value
        value=$(sysctl -n "$param" 2>/dev/null || echo "N/A")
        if [[ "$value" != "N/A" ]]; then
            log_info "${param} = ${value}"
        else
            log_warn "参数 ${param} 未设置"
            all_ok=false
        fi
    done

    if [[ "$all_ok" == "true" ]]; then
        log_success "所有关键内核参数已生效"
    else
        log_warn "部分参数可能未生效，请检查"
    fi
}

configure_limits() {
    log_step "配置系统资源限制"

    cat > "$LIMITS_CONF" << 'LIMITS_EOF'
# Enterprise Cloud Native Platform - System Limits
# Generated by 04-kernel.sh init script

*       soft    nofile    1048576
*       hard    nofile    1048576
*       soft    nproc     131072
*       hard    nproc     131072
*       soft    memlock   unlimited
*       hard    memlock   unlimited
*       soft    core      unlimited
*       hard    core      unlimited
*       soft    stack     unlimited
*       hard    stack     unlimited

root    soft    nofile    1048576
root    hard    nofile    1048576
root    soft    nproc     131072
root    hard    nproc     131072
root    soft    memlock   unlimited
root    hard    memlock   unlimited
LIMITS_EOF

    # 应用limits（当前session立即生效）
    ulimit -n 1048576 2>/dev/null || true
    ulimit -u 131072 2>/dev/null || true

    log_success "系统资源限制已配置"
}

configure_modules() {
    log_step "配置内核模块自动加载"

    cat > "$MODULES_CONF" << 'MODULES_EOF'
# Enterprise Cloud Native Platform - Kernel Modules
# Generated by 04-kernel.sh init script

# Docker/Kubernetes网络所需模块
br_netfilter
overlay
ip_vs
ip_vs_rr
ip_vs_wrr
ip_vs_sh
nf_conntrack
MODULES_EOF

    # 立即加载模块
    while read -r module; do
        module=$(echo "$module" | xargs)
        [[ -z "$module" || "$module" =~ ^# ]] && continue
        modprobe "$module" 2>/dev/null || log_warn "无法加载模块: $module"
    done < "$MODULES_CONF"

    log_success "内核模块配置已更新"
}

disable_swap() {
    log_step "检查Swap状态"

    local swap_usage
    swap_usage=$(swapon --show 2>/dev/null | grep -v "^NAME" | wc -l)

    if [[ "$swap_usage" -gt 0 ]]; then
        log_warn "检测到Swap已启用，Kubernetes建议关闭Swap"
        log_info "当前Swap状态:"
        swapon --show 2>/dev/null | tee -a "$LOG_FILE"

        # 注释掉/etc/fstab中的swap行
        sed -i '/\sswap\s/s/^/#/' /etc/fstab 2>/dev/null || true
        swapoff -a 2>/dev/null || true
        log_success "已关闭Swap"
    else
        log_success "Swap未启用，无需处理"
    fi
}

disable_firewall() {
    log_step "检查防火墙状态"

    if systemctl is-active firewalld >/dev/null 2>&1; then
        log_info "firewalld正在运行，集群部署阶段建议关闭"
        log_info "注意: 生产环境请根据安全策略配置防火墙规则"
        systemctl stop firewalld 2>/dev/null || true
        systemctl disable firewalld 2>/dev/null || true
        log_success "已停止并禁用firewalld"
    else
        log_success "firewalld未运行"
    fi

    # 确保iptables服务状态
    if systemctl is-active iptables >/dev/null 2>&1; then
        systemctl stop iptables 2>/dev/null || true
        systemctl disable iptables 2>/dev/null || true
    fi
}

# ========================= 主逻辑 =========================
main() {
    mkdir -p "$LOG_DIR"
    check_root
    check_lock
    detect_os

    log_step "阶段1-任务4: 内核参数优化"

    # 配置sysctl参数
    configure_sysctl

    # 应用sysctl参数
    apply_sysctl

    # 配置系统资源限制
    configure_limits

    # 配置内核模块
    configure_modules

    # 关闭Swap
    disable_swap

    # 关闭防火墙
    disable_firewall

    log_success "阶段1-任务4完成: 内核参数优化成功"
}

main "$@"
