#!/bin/bash
###############################################################################
# 脚本名称: 06-nfs.sh
# 功能描述: 配置NFS服务端，用于Kubernetes PV/PVC存储
# 适用系统: CentOS 7/8, Rocky Linux 8/9
# 依赖条件: root权限, 网络连接
# 作者: 运维平台团队
# 版本: 1.0.0
# 创建日期: 2026-05-09
###############################################################################
set -euo pipefail
umask 077

# ========================= 全局变量 =========================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LOG_DIR="${PROJECT_ROOT}/logs/01-init"
LOG_FILE="${LOG_DIR}/06-nfs_$(date +%Y%m%d_%H%M%S).log"
LOCK_FILE="/var/lock/06-nfs.lock"
NFS_EXPORT_BASE="${NFS_EXPORT_BASE:-/data/nfs}"
NFS_EXPORT_SUBDIRS=("shared" "registry" "mysql" "postgres" "redis" "elasticsearch" "minio" "jenkins")
NFS_SUBNET="${NFS_SUBNET:-10.0.0.0/8}"
NFS_OPTS="*(rw,sync,no_root_squash,no_subtree_check)"
NFS_EXPORTS_FILE="/etc/exports"

# ========================= 颜色定义 =========================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ========================= 日志函数 =========================
log_info()    { echo -e "${GREEN}[INFO]${NC}  $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }
log_step()    { echo -e "${CYAN}[STEP]${NC}  $(date '+%Y-%m-%d %H:%M:%S') === $* ===" | tee -a "$LOG_FILE"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"; }

# ========================= 错误处理 =========================
cleanup() {
    local exit_code=$?
    rm -f "$LOCK_FILE"
    if [[ $exit_code -ne 0 ]]; then
        log_error "脚本执行失败，退出码: $exit_code"
    fi
    return $exit_code
}
trap cleanup EXIT
trap 'log_error "收到信号，正在退出..."; exit 1' SIGINT SIGTERM

# ========================= 工具函数 =========================
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "此脚本必须以root权限运行"
        exit 1
    fi
}

check_lock() {
    if [[ -f "$LOCK_FILE" ]]; then
        local pid
        pid=$(cat "$LOCK_FILE" 2>/dev/null || true)
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            log_error "另一个实例正在运行 (PID: $pid)"
            exit 1
        fi
        log_warn "发现残留锁文件，已清理"
        rm -f "$LOCK_FILE"
    fi
    echo $$ > "$LOCK_FILE"
}

detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS_ID="${ID}"
        OS_VERSION="${VERSION_ID}"
        OS_NAME="${PRETTY_NAME}"
    fi
    log_info "检测到系统: ${OS_NAME:-Unknown}"
}

# ========================= NFS配置函数 =========================
install_nfs() {
    log_step "安装NFS服务"

    local packages=()
    case "${OS_ID}" in
        centos|rhel|rocky|almalinux)
            local os_version="${OS_VERSION%%.*}"
            if [[ "$os_version" -ge 8 ]]; then
                packages=(nfs-utils)
            else
                packages=(nfs-utils rpcbind)
            fi
            ;;
        *)
            packages=(nfs-utils)
            ;;
    esac

    local need_install=false
    for pkg in "${packages[@]}"; do
        if ! rpm -q "$pkg" >/dev/null 2>&1; then
            need_install=true
            break
        fi
    done

    if [[ "$need_install" == "true" ]]; then
        yum install -y "${packages[@]}" 2>>"$LOG_FILE"
        log_success "NFS软件包安装成功"
    else
        log_info "NFS软件包已安装，跳过"
    fi
}

create_export_dirs() {
    log_step "创建NFS导出目录"

    # 创建基础导出目录
    mkdir -p "$NFS_EXPORT_BASE"
    chmod 777 "$NFS_EXPORT_BASE"

    # 创建子目录
    for subdir in "${NFS_EXPORT_SUBDIRS[@]}"; do
        local full_path="${NFS_EXPORT_BASE}/${subdir}"
        if [[ ! -d "$full_path" ]]; then
            mkdir -p "$full_path"
            log_info "创建目录: $full_path"
        fi
        chmod 777 "$full_path"
        chown nobody:nobody "$full_path" 2>/dev/null || true
    done

    log_success "NFS导出目录已创建: ${NFS_EXPORT_BASE}"
}

configure_exports() {
    log_step "配置NFS导出表"

    # 备份原exports文件
    local backup="${NFS_EXPORTS_FILE}.bak.$(date +%Y%m%d)"
    if [[ -f "$NFS_EXPORTS_FILE" && ! -f "$backup" ]]; then
        cp "$NFS_EXPORTS_FILE" "$backup"
        log_info "已备份exports配置: $backup"
    fi

    # 移除旧的enterprise-platform配置
    if grep -q "# Enterprise Cloud Native Platform" "$NFS_EXPORTS_FILE" 2>/dev/null; then
        sed -i '/# Enterprise Cloud Native Platform/,/^$/d' "$NFS_EXPORTS_FILE"
        log_info "已清理旧的NFS配置"
    fi

    # 写入新的导出配置
    cat >> "$NFS_EXPORTS_FILE" << EXPORTS_EOF

# Enterprise Cloud Native Platform - NFS Exports
# Generated by 06-nfs.sh init script
# 网段限制: ${NFS_SUBNET}

# 共享存储目录
${NFS_EXPORT_BASE}/shared    ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)
${NFS_EXPORT_BASE}/registry  ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)
${NFS_EXPORT_BASE}/mysql     ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)
${NFS_EXPORT_BASE}/postgres  ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)
${NFS_EXPORT_BASE}/redis     ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)
${NFS_EXPORT_BASE}/elasticsearch ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)
${NFS_EXPORT_BASE}/minio     ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)
${NFS_EXPORT_BASE}/jenkins   ${NFS_SUBNET}(rw,sync,no_root_squash,no_subtree_check)

# 默认导出（所有子目录）
${NFS_EXPORT_BASE}           ${NFS_SUBNET}(ro,sync,no_subtree_check)
EXPORTS_EOF

    log_success "NFS导出配置已更新"
}

configure_firewall_nfs() {
    log_step "配置NFS防火墙规则"

    if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active firewalld >/dev/null 2>&1; then
        # 开放NFS相关端口
        firewall-cmd --permanent --add-service=nfs 2>/dev/null || true
        firewall-cmd --permanent --add-service=rpc-bind 2>/dev/null || true
        firewall-cmd --permanent --add-service=mountd 2>/dev/null || true
        firewall-cmd --reload 2>/dev/null || true
        log_success "防火墙NFS规则已添加"
    else
        log_info "firewalld未运行，跳过防火墙配置"
    fi
}

configure_nfs_sysctl() {
    log_step "配置NFS内核参数"

    local sysctl_conf="/etc/sysctl.d/99-nfs.conf"
    cat > "$sysctl_conf" << 'SYSCTL_EOF'
# NFS performance tuning
sunrpc.tcp_slot_table_entries = 128
sunrpc.tcp_max_slot_table_entries = 128
SYSCTL_EOF

    sysctl --system 2>&1 | tee -a "$LOG_FILE" || true
    log_success "NFS内核参数已配置"
}

start_nfs() {
    log_step "启动NFS服务"

    systemctl daemon-reload

    # 启用并启动相关服务
    local services=("rpcbind" "nfs-server")
    for svc in "${services[@]}"; do
        systemctl enable "$svc" 2>>"$LOG_FILE" || true
        systemctl restart "$svc" 2>>"$LOG_FILE" || true
    done

    # 等待服务启动
    sleep 2

    # 验证服务状态
    local all_running=true
    for svc in "${services[@]}"; do
        if systemctl is-active "$svc" >/dev/null 2>&1; then
            log_success "${svc} 服务运行正常"
        else
            log_error "${svc} 服务启动失败"
            all_running=false
        fi
    done

    if [[ "$all_running" == "false" ]]; then
        systemctl status "${services[@]}" --no-pager 2>&1 | tee -a "$LOG_FILE"
        return 1
    fi

    # 重新导出
    exportfs -ra 2>&1 | tee -a "$LOG_FILE" || true
    log_success "NFS导出已刷新"
}

verify_nfs() {
    log_step "验证NFS配置"

    # 显示导出列表
    log_info "当前NFS导出列表:"
    exportfs -v 2>&1 | tee -a "$LOG_FILE" || true

    # 检查目录权限
    log_info "导出目录权限检查:"
    for subdir in "${NFS_EXPORT_SUBDIRS[@]}"; do
        local full_path="${NFS_EXPORT_BASE}/${subdir}"
        if [[ -d "$full_path" ]]; then
            local perms
            perms=$(stat -c "%a %U:%G" "$full_path" 2>/dev/null || echo "unknown")
            log_info "  ${full_path} -> ${perms}"
        fi
    done

    # 显示挂载点
    log_info "NFS挂载信息:"
    showmount -e localhost 2>&1 | tee -a "$LOG_FILE" || true

    # 显示NFS服务状态
    log_info "NFS服务状态:"
    rpcinfo -p localhost 2>&1 | tee -a "$LOG_FILE" || true
}

# ========================= 主逻辑 =========================
main() {
    mkdir -p "$LOG_DIR"
    check_root
    check_lock
    detect_os

    log_step "阶段1-任务6: NFS服务端配置"

    # 安装NFS
    install_nfs

    # 创建导出目录
    create_export_dirs

    # 配置导出表
    configure_exports

    # 配置防火墙
    configure_firewall_nfs

    # 配置内核参数
    configure_nfs_sysctl

    # 启动NFS服务
    start_nfs

    # 验证配置
    verify_nfs

    log_success "阶段1-任务6完成: NFS服务端配置成功"
    log_info "NFS导出基础路径: ${NFS_EXPORT_BASE}"
    log_info "客户端挂载命令: mount -t nfs <nfs-server-ip>:${NFS_EXPORT_BASE}/<subdir> /mnt"
}

main "$@"
